# Generated by Django 5.2.6 on 2026-09-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_change', models.FloatField(default=0)),
                ('discount_change', models.FloatField(default=0)),
                ('marketing_change', models.FloatField(default=0)),
                ('demand_change', models.FloatField(default=0)),
                ('baseline_revenue', models.FloatField(default=0)),
                ('baseline_profit', models.FloatField(default=0)),
                ('baseline_units', models.FloatField(default=0)),
                ('scenario_revenue', models.FloatField(default=0)),
                ('scenario_profit', models.FloatField(default=0)),
                ('scenario_units', models.FloatField(default=0)),
                ('revenue_change', models.FloatField(default=0)),
                ('profit_change', models.FloatField(default=0)),
                ('units_change', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('decision', models.CharField(choices=[('Recommended', 'Recommended'), ('High Revenue', 'High Revenue'), ('Lower Profit', 'Lower Profit'), ('Not Recommended', 'Not Recommended'), ('Review', 'Review')], default='Review', max_length=30)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_scenarios', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='data_management.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
