# Generated by Django 5.2.6 on 2026-09-13 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('source', models.CharField(choices=[('Forecasting', 'Forecasting'), ('Anomaly Detection', 'Anomaly Detection'), ('Customer Risk', 'Customer Risk'), ('Opportunity Detection', 'Opportunity Detection'), ('Root Cause Analysis', 'Root Cause Analysis'), ('Recommendation Engine', 'Recommendation Engine'), ('Scenario Planning', 'Scenario Planning'), ('System', 'System')], default='System', max_length=40)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('metric_name', models.CharField(blank=True, max_length=100)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='data_management.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
