# Generated by Django 5.2.6 on 2026-09-13 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0002_businessalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Alert', 'Alert'), ('Scenario', 'Scenario'), ('Manual', 'Manual')], default='Recommendation', max_length=30)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Dismissed', 'Dismissed')], default='Open', max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_impact', models.CharField(blank=True, max_length=255)),
                ('impact_score', models.FloatField(default=0)),
                ('recommendation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_actions', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_actions', to='data_management.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
