# Generated by Django 5.2.6 on 2026-09-13 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0003_businessaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_revenue_change', models.FloatField(default=0)),
                ('expected_profit_change', models.FloatField(default=0)),
                ('expected_units_change', models.FloatField(default=0)),
                ('expected_impact_score', models.FloatField(default=0)),
                ('actual_revenue_change', models.FloatField(default=0)),
                ('actual_profit_change', models.FloatField(default=0)),
                ('actual_units_change', models.FloatField(default=0)),
                ('revenue_accuracy', models.FloatField(default=0)),
                ('profit_accuracy', models.FloatField(default=0)),
                ('units_accuracy', models.FloatField(default=0)),
                ('actual_impact_score', models.FloatField(default=0)),
                ('impact_status', models.CharField(choices=[('Pending', 'Pending'), ('Measured', 'Measured'), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Pending', max_length=20)),
                ('measurement_start', models.DateField(blank=True, null=True)),
                ('measurement_end', models.DateField(blank=True, null=True)),
                ('analysis_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_impact', to='decision_intelligence.businessaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_impacts', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_impacts', to='data_management.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
