# Generated by Django 5.2.6 on 2026-09-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_intelligence', '0004_decisionimpact'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaction',
            name='expected_profit_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessaction',
            name='expected_revenue_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessaction',
            name='expected_units_change',
            field=models.FloatField(default=0),
        ),
    ]
