# Generated by Django 5.2.6 on 2026-09-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_intelligence', '0005_businessaction_expected_profit_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaction',
            name='recommendation_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
