# Generated by Django 5.2.6 on 2026-09-13 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0006_businessaction_recommendation_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_title', models.CharField(max_length=255)),
                ('recommendation_category', models.CharField(blank=True, default='', max_length=50)),
                ('recommendation_source', models.CharField(blank=True, default='', max_length=100)),
                ('feedback', models.CharField(choices=[('Useful', 'Useful'), ('Not Useful', 'Not Useful'), ('Partially Useful', 'Partially Useful')], max_length=30)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], default=3)),
                ('comment', models.TextField(blank=True)),
                ('recommendation_score', models.FloatField(default=0)),
                ('priority', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_records', to='decision_intelligence.businessaction')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='data_management.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
