# Generated by Django 5.2.6 on 2026-09-13 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('Business', 'Business Report'), ('Sales', 'Sales Report'), ('Customer', 'Customer Report'), ('Product', 'Product Report'), ('Regional', 'Regional Report'), ('Financial', 'Financial Report'), ('Marketing', 'Marketing Report'), ('Returns', 'Returns Report'), ('Decision', 'Decision Intelligence Report')], default='Business', max_length=30)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], default='PDF', max_length=10)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Processing', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('total_recommendations', models.PositiveIntegerField(default=0)),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('business_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_management.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
