# Generated by Django 5.2.6 on 2026-09-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='business_score',
            new_name='average_decision_score',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='total_alerts',
            new_name='critical_recommendations',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_format',
        ),
        migrations.AddField(
            model_name='report',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/excel/'),
        ),
        migrations.AddField(
            model_name='report',
            name='feedback_learning_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='high_recommendations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='learning_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='output_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('Both', 'Both')], default='PDF', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdf/'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_management.dataset'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Business Summary', 'Business Summary'), ('Sales Report', 'Sales Report'), ('Customer Report', 'Customer Report'), ('Product Report', 'Product Report'), ('Regional Report', 'Regional Report'), ('Financial Report', 'Financial Report'), ('Marketing Report', 'Marketing Report'), ('Decision Report', 'Decision Report'), ('Executive Report', 'Executive Report')], default='Business Summary', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Generated', max_length=20),
        ),
    ]
