# Generated by Django 5.2.6 on 2026-09-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('reporting', '0003_alter_report_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('Executive', 'Executive'), ('Sales', 'Sales'), ('Customer', 'Customer'), ('Product', 'Product'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns'), ('Operational', 'Operational')], default='Executive', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('output_format', models.CharField(choices=[('Dashboard', 'Dashboard'), ('PDF', 'PDF'), ('Excel', 'Excel')], default='Dashboard', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('kpis', models.JSONField(blank=True, default=dict)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('charts', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_reports', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_reports', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_reports', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['dataset', 'dataset_version'], name='reporting_a_dataset_9ba68f_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['created_by'], name='reporting_a_created_76eff1_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['report_type'], name='reporting_a_report__ba0cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['status'], name='reporting_a_status_660cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['output_format'], name='reporting_a_output__d7bbea_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['generated_at'], name='reporting_a_generat_aa97b5_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedreport',
            index=models.Index(fields=['created_at'], name='reporting_a_created_988b4b_idx'),
        ),
    ]
