# Generated by Django 5.2.6 on 2026-09-22 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('reporting', '0004_automatedreport_delete_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('Executive', 'Executive'), ('Sales', 'Sales'), ('Customer', 'Customer'), ('Product', 'Product'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns'), ('Operational', 'Operational')], default='Executive', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('output_format', models.CharField(choices=[('Dashboard', 'Dashboard'), ('PDF', 'PDF'), ('Excel', 'Excel')], default='Dashboard', max_length=20)),
                ('selected_columns', models.JSONField(blank=True, default=list)),
                ('selected_metrics', models.JSONField(blank=True, default=list)),
                ('selected_dimensions', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('sort_configuration', models.JSONField(blank=True, default=dict)),
                ('chart_configuration', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('kpis', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('charts', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='reporting_c_dataset_62f49e_idx'), models.Index(fields=['created_by'], name='reporting_c_created_efda18_idx'), models.Index(fields=['report_type'], name='reporting_c_report__0d4cd5_idx'), models.Index(fields=['status'], name='reporting_c_status_46d5f0_idx'), models.Index(fields=['output_format'], name='reporting_c_output__d1fcd2_idx'), models.Index(fields=['generated_at'], name='reporting_c_generat_08cffa_idx'), models.Index(fields=['created_at'], name='reporting_c_created_8c05e7_idx')],
            },
        ),
    ]
