# Generated by Django 5.2.6 on 2026-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_customreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedreport',
            name='kpis',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
