from django.conf import settings
from django.db import models


class Recommendation(models.Model):
    """
    Stores actionable business recommendations generated by
    the Decision Intelligence module.
    """

    CATEGORY_CHOICES = [
        ("Sales", "Sales"),
        ("Customer", "Customer"),
        ("Product", "Product"),
        ("Regional", "Regional"),
        ("Marketing", "Marketing"),
        ("Financial", "Financial"),
        ("Returns", "Returns"),
        ("Operational", "Operational"),
        ("General", "General"),
    ]

    PRIORITY_CHOICES = [
        ("Low", "Low"),
        ("Medium", "Medium"),
        ("High", "High"),
        ("Critical", "Critical"),
    ]

    IMPACT_CHOICES = [
        ("Low", "Low"),
        ("Medium", "Medium"),
        ("High", "High"),
    ]

    STATUS_CHOICES = [
        ("New", "New"),
        ("Reviewed", "Reviewed"),
        ("Accepted", "Accepted"),
        ("Rejected", "Rejected"),
        ("Completed", "Completed"),
    ]

    dataset = models.ForeignKey(
        "data_management.Dataset",
        on_delete=models.CASCADE,
        related_name="recommendations",
    )

    dataset_version = models.ForeignKey(
        "data_management.DatasetVersion",
        on_delete=models.CASCADE,
        related_name="recommendations",
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recommendations",
    )

    title = models.CharField(max_length=255)

    category = models.CharField(
        max_length=50,
        choices=CATEGORY_CHOICES,
        default="General",
    )

    description = models.TextField()

    supporting_insight = models.TextField(
        blank=True,
        default="",
    )

    recommended_action = models.TextField()

    expected_outcome = models.TextField(
        blank=True,
        default="",
    )

    priority = models.CharField(
        max_length=20,
        choices=PRIORITY_CHOICES,
        default="Medium",
    )

    impact_level = models.CharField(
        max_length=20,
        choices=IMPACT_CHOICES,
        default="Medium",
    )

    confidence = models.FloatField(
        default=0,
        help_text="Recommendation confidence percentage from 0 to 100.",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="New",
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["dataset", "dataset_version"]),
            models.Index(fields=["category"]),
            models.Index(fields=["priority"]),
            models.Index(fields=["status"]),
            models.Index(fields=["created_at"]),
        ]

    def __str__(self):
        return self.title